version: 1.0.0.{build}
image: Visual Studio 2019

configuration: Release
platform: AnyCPU

before_build:
- cmd: >-
    nuget restore -PackagesDirectory ../packages
    
    msbuild.exe

build:
  verbosity: minimal